spring.application.name=livequiz

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:livequiz}
spring.datasource.username=${DB_USER:livequiz}
spring.datasource.password=${DB_PASSWORD:livequiz}

spring.jpa.hibernate.ddl-auto=update
